services:

  internal-db-service:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${SS_INTERNAL_DB_NAME}
      POSTGRES_USER: ${SS_INTERNAL_DB_USER}
      POSTGRES_PASSWORD: ${SS_INTERNAL_DB_PASS}
    healthcheck:
    # Данная команда убирает ошибку FATAL dose not exist user root
    # Мы запускаем постгрес с нужной базой данных и нужным пользователем
    # А по умолчанию он пытается это сделать от root, которого нет
    # Аналогично и с базой данных airflow
      test: [ "CMD-SHELL", "pg_isready -d ${SS_INTERNAL_DB_NAME} -U ${SS_INTERNAL_DB_USER} " ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${SS_INTERNAL_DB_PORT}:5432
    

  alembic-migration:
    build:
      context: .
      dockerfile: alembic.Dockerfile
    environment:
      DATABASE_USER: ${SS_INTERNAL_DB_USER}
      DATABASE_PASS: ${SS_INTERNAL_DB_PASS}
      DATABASE_NAME: ${SS_INTERNAL_DB_NAME}
      SERVICE_URL: ${SS_INTERNAL_DB_URL}
    depends_on:
      internal-db-service:
        condition: service_healthy
  
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    # restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}

  api-service:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - INTERNAL_DB_NAME=${SS_INTERNAL_DB_NAME}
      - INTERNAL_DB_USER=${SS_INTERNAL_DB_USER}
      - INTERNAL_DB_PASS=${SS_INTERNAL_DB_PASS}
      - INTERNAL_DB_URL=${SS_INTERNAL_DB_URL}

    ports:
      - ${SS_BACKEND_PORT}:8080